Controllers/CitaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcVeterinaria.Data;
using MvcVeterinaria.Models;

namespace MvcVeterinaria.Controllers
{
    public class CitaController : Controller
    {
        private readonly MvcVeterinariaContext _context;

        public CitaController(MvcVeterinariaContext context)
        {
            _context = context;
        }

        // GET: Cita
        public async Task<IActionResult> Index()
        {
            var mvcVeterinariaContext = _context.Cita.Include(c => c.Medicamento).Include(c => c.Veterinario);
            return View(await mvcVeterinariaContext.ToListAsync());
        }

        // GET: Cita/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Medicamento)
                .Include(c => c.Veterinario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // GET: Cita/Create
        public IActionResult Create()
        {
            var mc = new  MascotaController();
            List<string> n =  mc.obtenerNombres();
            SelectList list = new SelectList(n);
             ViewData["MascotaID"] = list;

            var veterinarioQuery = from v in _context.Veterinario orderby v.Nombre select v;
            ViewData["VeterinarioID"] = new SelectList(veterinarioQuery.AsNoTracking(), "Id", "Nombre");
            var MedicamentoQuery=  from me in _context.Medicamento orderby me.Nombre select me;
            ViewData["MedicamentoID"] = new SelectList(MedicamentoQuery, "Id", "Nombre");
           
            return View();
        }

        // POST: Cita/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Descripcion,MascotaID,VeterinarioID,MedicamentoID")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cita);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           var mc = new  MascotaController();
            List<string> n =  mc.obtenerNombres();
            SelectList list = new SelectList(n);
             ViewData["MascotaID"] = list;

            var veterinarioQuery = from v in _context.Veterinario orderby v.Nombre select v;
            ViewData["VeterinarioID"] = new SelectList(veterinarioQuery.AsNoTracking(), "Id", "Nombre");
            var MedicamentoQuery=  from me in _context.Medicamento orderby me.Nombre select me;
            ViewData["MedicamentoID"] = new SelectList(MedicamentoQuery, "Id", "Nombre");
            return View(cita);
        }

        // GET: Cita/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita.FindAsync(id);
            if (cita == null)
            {
                return NotFound();
            }
           var mc = new  MascotaController();
            List<string> n =  mc.obtenerNombres();
            SelectList list = new SelectList(n);
             ViewData["MascotaID"] = list;

            var veterinarioQuery = from v in _context.Veterinario orderby v.Nombre select v;
            ViewData["VeterinarioID"] = new SelectList(veterinarioQuery.AsNoTracking(), "Id", "Nombre");
            var MedicamentoQuery=  from me in _context.Medicamento orderby me.Nombre select me;
            ViewData["MedicamentoID"] = new SelectList(MedicamentoQuery, "Id", "Nombre");
            return View(cita);
        }

        // POST: Cita/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Descripcion,MascotaID,VeterinarioID,MedicamentoID")] Cita cita)
        {
            if (id != cita.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CitaExists(cita.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var mc = new  MascotaController();
            List<string> n =  mc.obtenerNombres();
            SelectList list = new SelectList(n);
             ViewData["MascotaID"] = list;

            var veterinarioQuery = from v in _context.Veterinario orderby v.Nombre select v;
            ViewData["VeterinarioID"] = new SelectList(veterinarioQuery.AsNoTracking(), "Id", "Nombre");
            var MedicamentoQuery=  from me in _context.Medicamento orderby me.Nombre select me;
            ViewData["MedicamentoID"] = new SelectList(MedicamentoQuery, "Id", "Nombre");
            return View(cita);
        }

        // GET: Cita/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Medicamento)
                .Include(c => c.Veterinario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // POST: Cita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cita = await _context.Cita.FindAsync(id);
            _context.Cita.Remove(cita);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CitaExists(int id)
        {
            return _context.Cita.Any(e => e.Id == id);
        }
    }
}

Controllers/MascotaController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MvcVeterinaria.Models;

namespace MvcVeterinaria.Controllers
{
    public class MascotaController : Controller
    {
        static List<Mascota> ListaMascotas = new List<Mascota>();

        public static int Identificador = 1;
        Mascota mascota = new Mascota();

        public IActionResult Index()
        {
            List<Mascota> listaOrdenada = ListaMascotas.OrderBy(p => p.Id).ToList();

            var model = listaOrdenada;
            return View("Index", model);
        }

        public IActionResult Create()
        {
            ViewBag.Iden = Identificador;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Models.Mascota mascota)
        {
            if (ModelState.IsValid)
            {

                ListaMascotas.Add(mascota);
                Identificador++;
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Iden = Identificador;
            return View();
        }

        public void ObtenerDatos(int Id)
        {
            int pos = ListaMascotas.FindIndex(p => p.Id == Id);
            mascota.Id = ListaMascotas[pos].Id;
            mascota.Nombre = ListaMascotas[pos].Nombre;
            mascota.Edad = ListaMascotas[pos].Edad;
            mascota.Dueño = ListaMascotas[pos].Dueño;

        }
        public List<string> obtenerNombres(){
             List<string> nom =new List<string>();
             string name="no hay nada";

             for (var i = 0; i < ListaMascotas.Count(); i++)
             { 

                 name = ListaMascotas[i].Nombre.ToString();
                 nom.Add(name);
                 
             }

             
             return nom;
        }


        public IActionResult Details(int Id)
        {


            ObtenerDatos(Id);
            return View(mascota);


        }

        public IActionResult Edit(int Id)
        {

            ObtenerDatos(Id);
            return View(mascota);

        }

        [HttpPost]
        public IActionResult Edit(int Id, Models.Mascota mascota)
        {

            if (ModelState.IsValid)
            {
                ObtenerDatos(Id);
                int pos = ListaMascotas.FindIndex(p => p.Id == Id);
                ListaMascotas.RemoveAt(pos);
                ListaMascotas.Add(mascota);
                return RedirectToAction(nameof(Index));
            }
            return View(mascota);
 
        } 

        public IActionResult Delete(int Id)
        {


            ObtenerDatos(Id);
            return View(mascota);

        }

        [HttpPost]
        public IActionResult Delete(int Id, Models.Mascota mascota)
        {
            ObtenerDatos(Id);
            int pos = ListaMascotas.FindIndex(p => p.Id == Id);
            ListaMascotas.RemoveAt(pos);
            return RedirectToAction(nameof(Index));

        }
    }
}

Controllers/MedicamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcVeterinaria.Data;
using MvcVeterinaria.Models;

namespace MvcVeterinaria.Controllers
{
    public class MedicamentoController : Controller
    {
        private readonly MvcVeterinariaContext _context;

        public MedicamentoController(MvcVeterinariaContext context)
        {
            _context = context;
        }

        // GET: Medicamento
        public async Task<IActionResult> Index()
        {
            return View(await _context.Medicamento.ToListAsync());
        }

        // GET: Medicamento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicamento == null)
            {
                return NotFound();
            }

            return View(medicamento);
        }

        // GET: Medicamento/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medicamento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Administracion,Dosis")] Medicamento medicamento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicamento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicamento);
        }

        // GET: Medicamento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamento.FindAsync(id);
            if (medicamento == null)
            {
                return NotFound();
            }
            return View(medicamento);
        }

        // POST: Medicamento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Administracion,Dosis")] Medicamento medicamento)
        {
            if (id != medicamento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicamentoExists(medicamento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicamento);
        }

        // GET: Medicamento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicamento == null)
            {
                return NotFound();
            }

            return View(medicamento);
        }

        // POST: Medicamento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medicamento = await _context.Medicamento.FindAsync(id);
            _context.Medicamento.Remove(medicamento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicamentoExists(int id)
        {
            return _context.Medicamento.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcVeterinaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
@*liberias para las alertas*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <link href="http://tristanedwards.me/u/SweetAlert/lib/sweet-alert.css" rel="stylesheet" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script> 
@*liberias para lla ultima version de bootstrap*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcVeterinaria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown text-black-50">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Registro
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-action="Index" asp-controller="Mascota" asp-area="">
                                Mascotas
                            </a>
                            <a class="dropdown-item" asp-action="Index" asp-controller="Veterinario" asp-area="">
                                Veterinarios

                            </a>
                             <a class="dropdown-item" asp-action="Index" asp-controller="Medicamento" asp-area="">
                                Medicamentos

                            </a>
                            <a class="dropdown-item" asp-action="Index" asp-controller="Cita" asp-area="">
                               Citas

                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcVeterinaria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>